# Generated by Django 3.2.5 on 2021-09-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=500)),
                ('unit_price', models.IntegerField()),
                ('ingredients', models.TextField(max_length=500)),
                ('food_description', models.TextField(default='', max_length=500)),
                ('image', models.TextField()),
                ('origen', models.TextField(default='', max_length=500)),
            ],
        ),
    ]
